# Generated by Django 5.0.3 on 2024-03-13 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Empresa', models.CharField(max_length=100)),
                ('RNC_Empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Usuario', models.CharField(max_length=100)),
                ('Apellido_Usuario', models.CharField(max_length=100)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.cliente')),
            ],
        ),
    ]
